<<<<<<< HEAD
import SocialMediaIcon from '@/public/affiliate/socialmedia.svg';
=======
import SocialMediaIcon from '@/public/affiliate/socialMedia.svg';
>>>>>>> 1b46ec4 (add affiliate)
import BlogIcon from '@/public/affiliate/blog.svg';
import WebsiteIcon from '@/public/affiliate/website.svg';
import OtherIcon from '@/public/affiliate/other.svg';

export const partnerConditions = [
    {
        icon: SocialMediaIcon,
        title: "Social Media",
        text: "Promote on social media, engage followers, and earn commissions as an affiliate by sharing your unique referral link with captivating content."
    },
    {
        icon: BlogIcon,
        title: "Blog",
        text: "Share affiliate links in blog posts, provide valuable insights, and earn commissions from conversions generated by your engaging content."
    },
    {
        icon: WebsiteIcon,
        title: "Website",
        text: "Feature affiliate links on your website, drive traffic through targeted promotions, and earn commissions from successful conversions."
    },
    {
        icon: OtherIcon,
        title: "Other",
        text: "Leverage your affiliate links with your audience, and earn commissions through their engagement and conversions."
    },
]