import Header from '@/compoents/Header'
import Footer from '@/compoents/Footer'
import Head from 'next/head'
import Image from 'next/image'
import Socials from '@/compoents/Socials'
import ComingSoon from '@/compoents/ComingSoon'

export default function Home() {
  return (
    <>
      <Head>
        <title>Cyberyal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <main className="wrapper">
        <Header />
        <div className="content">
          <Socials />
          <ComingSoon />
        </div>
        <Footer />
      </main>
    </>
  )
}
